name: RDP Zerotier

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Cài ZeroTier
        run: choco install zerotier-one -y

      - name: Join ZeroTier Network
        shell: powershell
        run: |
          Start-Sleep -Seconds 5

          # Start đúng service
          net start ZeroTierOneService

          Start-Sleep -Seconds 10

          # Join network (dùng full path)
          & "C:\Program Files (x86)\ZeroTier\One\zerotier-cli.bat" join b103a835d2b22276

          Start-Sleep -Seconds 5

          # Kiểm tra trạng thái
          & "C:\Program Files (x86)\ZeroTier\One\zerotier-cli.bat" listnetworks

      - name: Tạo User + bật RDP
        shell: powershell
        run: |
          $password = ConvertTo-SecureString "DepTraiCuTo@0909Aa!" -AsPlainText -Force
          New-LocalUser "cuong" -Password $password -FullName "cuong"

          Add-LocalGroupMember -Group "Administrators" -Member "cuong"
          Add-LocalGroupMember -Group "Remote Desktop Users" -Member "cuong"

          reg add "HKLM\System\CurrentControlSet\Control\Terminal Server" /v fDenyTSConnections /t REG_DWORD /d 0 /f
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      - name: Lấy IP ZeroTier
        shell: powershell
        run: |
          Start-Sleep -Seconds 15

          ipconfig

          Write-Host "=============================="
          Write-Host "Tìm IP dạng 10.x.x.x (ZeroTier)"
          Write-Host "USER: cuong"
          Write-Host "PASS: DepTraiCuTo@0909Aa!"
          Write-Host "=============================="

      - name: Giữ máy 6 tiếng
        shell: powershell
        run: Start-Sleep -Seconds 21600
