name: RDP Zerotier

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Cài ZeroTier
        run: |
          choco install zerotier-one -y

      - name: Join Network
        shell: powershell
        run: |
          net start ZeroTierOne
          Start-Sleep -Seconds 10

          zerotier-cli join b103a835d2b22276

          Write-Host "Đã join network, vào https://my.zerotier.com để approve"

      - name: Tạo user + bật RDP
        shell: powershell
        run: |
          $password = ConvertTo-SecureString "DepTraiCuTo@0909Aa!" -AsPlainText -Force
          New-LocalUser "cuong" -Password $password -FullName "cuong"

          Add-LocalGroupMember -Group "Administrators" -Member "cuong"
          Add-LocalGroupMember -Group "Remote Desktop Users" -Member "cuong"

          reg add "HKLM\System\CurrentControlSet\Control\Terminal Server" /v fDenyTSConnections /t REG_DWORD /d 0 /f
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      - name: Lấy IP ZeroTier
        shell: powershell
        run: |
          Start-Sleep -Seconds 15

          $ip = ipconfig | Select-String "ZeroTier" -Context 0,5
          Write-Host "=============================="
          Write-Host "IP Zerotier (tìm trong log):"
          Write-Host $ip
          Write-Host "USER: cuong"
          Write-Host "PASS: DepTraiCuTo@0909Aa!"
          Write-Host "=============================="

      - name: Giữ máy 6 tiếng
        shell: powershell
        run: Start-Sleep -Seconds 21600
