name: Parsec Auto Login

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Tạo User
        shell: powershell
        run: |
          $password = ConvertTo-SecureString "DepTraiCuTo@0909Aa!" -AsPlainText -Force
          New-LocalUser "cuong" -Password $password -FullName "cuong"
          Add-LocalGroupMember -Group "Administrators" -Member "cuong"

      - name: Cài Parsec
        shell: powershell
        run: |
          $url = "https://builds.parsecgaming.com/package/parsec-windows.exe"
          $output = "$env:TEMP\parsec-installer.exe"
          Invoke-WebRequest -Uri $url -OutFile $output
          Start-Process -FilePath $output -ArgumentList "/silent", "/quiet", "/norestart" -Wait
          Start-Sleep -Seconds 15

      - name: Đăng nhập Parsec
        shell: powershell
        run: |
          Start-Sleep -Seconds 10
          $parsecd = "C:\Program Files\Parsec\parsecd.exe"
          & $parsecd account login --email "${{ secrets.PARSEC_EMAIL }}" --password "${{ secrets.PARSEC_PASS }}"
          Start-Sleep -Seconds 5
          & $parsecd host enable
          & $parsecd host name "GitHub-Runner"
          Start-Sleep -Seconds 5
          
          Write-Host "=============================="
          Write-Host "Đã đăng nhập & bật Hosting!"
          Write-Host "Máy sẽ hiện trong App Parsec của bạn"
          Write-Host "=============================="

      - name: Giữ máy 6 tiếng
        shell: powershell
        run: Start-Sleep -Seconds 21600
